import fs from 'node:fs';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import ts from 'typescript';import vm from 'node:vm';import initSqlJs from 'sql.js';
const sql=new DatabaseSync(':memory:');sql.exec("CREATE TABLE members(id TEXT PRIMARY KEY,role TEXT,status TEXT)");sql.exec(fs.readFileSync('drizzle/0015_safe_skin.sql','utf8'));sql.exec("INSERT INTO members VALUES('owner','owner','active')");
const objects=new Map();let role='owner';const runtime={database:()=>({async batch(statements){sql.exec('BEGIN');try{const result=[];for(const s of statements)result.push(await s.run());sql.exec('COMMIT');return result}catch(e){sql.exec('ROLLBACK');throw e}},prepare(q){let args=[];return {bind(...v){args=v;return this},async first(){return sql.prepare(q).get(...args)},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {meta:sql.prepare(q).run(...args)}}}}}),bucket:()=>({async put(k,v){objects.set(k,v)},async get(k){return objects.has(k)?{json:async()=>JSON.parse(objects.get(k))}:null},async delete(k){for(const key of Array.isArray(k)?k:[k])objects.delete(key)},async list({prefix,cursor}){const keys=[...objects.keys()].filter(k=>k.startsWith(prefix)&&(!cursor||k>cursor)).sort();return {objects:keys.slice(0,1).map(key=>({key})),truncated:keys.length>1,cursor:keys[0]}}}),workspaceAccess:async()=>role===null?{response:Response.json({}, {status:401})}:{member:{id:'owner',role}}};globalThis.lakeTest=runtime;
async function load(path,names){const src=fs.readFileSync(path,'utf8').replace(/^import .*;\s*$/gm,'');const code='const {'+names.join(',')+'}=globalThis.lakeTest;\n'+src;return import('data:text/javascript;base64,'+Buffer.from(ts.transpileModule(code,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText).toString('base64'))}
Object.assign(runtime,await load('lib/data-lake.ts',['database','bucket','workspaceAccess']));const api=await load('app/api/data-lake/route.ts',['database','bucket','lakeOwner','lakeJson','audit','validateData','validSheetName','isId','readSheet','hashToken','deleteWorkbookObjects','LAKE_LIMITS']);const feed=await load('app/api/data-lake/feed/[id]/route.ts',['database','lakeJson','hashToken','readSheet','csv','audit']);

// A legacy single-sheet dataset and its feed credential exist before the workbook migration runs.
const legacyId='11111111-2222-4333-8444-555555555555',legacyToken='ab'.repeat(32);objects.set('data-lake/'+legacyId,JSON.stringify({columns:['Old'],rows:[['kept']]}));
sql.prepare("INSERT INTO lake_datasets (id,name,columns,row_count,object_key,created,owner) VALUES (?,?,?,?,?,?,?)").run(legacyId,'Legacy','["Old"]',1,'data-lake/'+legacyId,1,'owner');
sql.prepare('INSERT INTO lake_tokens (id,dataset,hash,owner,expires,created) VALUES (?,?,?,?,?,?)').run('legacy-token',legacyId,await runtime.hashToken(legacyToken),'owner',9999999999999,1);
sql.exec(fs.readFileSync('drizzle/0016_foamy_silhouette.sql','utf8'));sql.exec(fs.readFileSync('drizzle/0016_foamy_silhouette.sql','utf8').split('--> statement-breakpoint').slice(-2).join(''));
const request=(d,origin='https://test')=>new Request('https://test/api/data-lake',{method:'POST',headers:{origin},body:JSON.stringify(d)});const get=q=>api.GET(new Request('https://test/api/data-lake'+(q?'?'+q:'')));
const fetchFeed=(sheet,token)=>feed.GET(new Request('https://test/api/data-lake/feed/'+sheet,{headers:{Authorization:'Basic '+btoa('datalake:'+token)}}),{params:Promise.resolve({id:sheet})});
for(const r of [null,'member','admin']){role=r;assert.equal((await get()).status,r===null?401:403);assert.equal((await api.POST(request({action:'import-begin',name:'x',sheetCount:1}))).status,r===null?401:403)}role='owner';assert.equal((await api.POST(request({},'https://evil'))).status,403);
let list=await(await get()).json();assert.equal(list.workbooks.length,1);assert.equal(list.workbooks[0].id,legacyId);assert.equal(list.workbooks[0].sheets[0].id,legacyId);assert.equal(list.workbooks[0].sheets[0].name,'Sheet 1');assert.equal(list.limits.workbookSheets,25);
let res=await fetchFeed(legacyId,legacyToken);assert.equal(res.status,200);assert.match(await res.text(),/kept/);
assert.equal(sql.prepare('SELECT COUNT(*) n FROM lake_workbooks').get().n,1,'rerunning the upgrade copies nothing twice');
console.log('PASS owner-only access, CSRF, and non-destructive upgrade of legacy datasets with working feed credentials.');

// Staged import: begin → one worksheet per request → commit. Nothing is listed until commit succeeds.
const sheetA={columns:['Item','Quantity'],rows:[['Painting',3],['=CMD()',1]]},sheetB={columns:['Region','Sales'],rows:[['North',10]]},sheetC={columns:['Note'],rows:[]};
const begin=async(name,sheetCount)=>(await(await api.POST(request({action:'import-begin',name,sheetCount}))).json());
assert.equal((await api.POST(request({action:'import-begin',name:'',sheetCount:1}))).status,400);assert.equal((await api.POST(request({action:'import-begin',name:'x',sheetCount:26}))).status,400);
let wb=await begin('Sales book',3);assert.ok(wb.id);
assert.equal((await api.POST(request({action:'import-sheet',workbook:wb.id,position:0,name:'Summary',data:sheetA}))).status,200);
assert.equal((await api.POST(request({action:'import-sheet',workbook:wb.id,position:0,name:'Again',data:sheetA}))).status,409,'duplicate position');
assert.equal((await api.POST(request({action:'import-sheet',workbook:wb.id,position:3,name:'Beyond',data:sheetA}))).status,400,'position beyond declared count');
assert.equal((await api.POST(request({action:'import-sheet',workbook:wb.id,position:1,name:'Bad',data:{columns:['a','A'],rows:[]}}))).status,400,'duplicate headers');
assert.equal((await api.POST(request({action:'import-sheet',workbook:wb.id,position:1,name:'Wide',data:{columns:Array.from({length:101},(_,i)=>'c'+i),rows:[]}}))).status,400,'too many columns');
res=await api.POST(request({action:'import-commit',workbook:wb.id}));assert.equal(res.status,409);assert.equal((await res.json()).incomplete,true);
list=await(await get()).json();assert.equal(list.workbooks.length,1,'incomplete import is not listed');
assert.equal((await api.POST(request({action:'import-sheet',workbook:wb.id,position:1,name:'Regions',data:sheetB}))).status,200);
assert.equal((await api.POST(request({action:'import-sheet',workbook:wb.id,position:2,name:'Notes',data:sheetC}))).status,200);
res=await api.POST(request({action:'import-commit',workbook:wb.id}));assert.equal(res.status,200);const committed=await res.json();assert.equal(committed.id,wb.id);assert.ok(committed.revision);
assert.equal((await api.POST(request({action:'import-sheet',workbook:wb.id,position:0,name:'Late',data:sheetA}))).status,404,'closed import rejects sheets');
list=await(await get()).json();const saved=list.workbooks.find(w=>w.id===wb.id);assert.equal(saved.sheet_count,3);assert.deepEqual(saved.sheets.map(s=>s.name),['Summary','Regions','Notes']);assert.deepEqual(saved.sheets.map(s=>s.position),[0,1,2]);assert.equal(saved.sheets[2].row_count,0);
const [summary,regions]=saved.sheets;res=await get('sheet='+summary.id);assert.equal(res.status,200);let read=await res.json();assert.deepEqual(read.data,sheetA);assert.equal(read.workbook.revision,committed.revision);assert.equal(read.sheet.name,'Summary');
const abandoned=await begin('Abandoned',2);await api.POST(request({action:'import-sheet',workbook:abandoned.id,position:0,name:'S',data:sheetA}));assert.equal(objects.size,5);assert.equal((await api.POST(request({action:'import-abort',workbook:abandoned.id}))).status,200);assert.equal(objects.size,4);assert.equal(sql.prepare('SELECT COUNT(*) n FROM lake_workbooks WHERE id=?').get(abandoned.id).n,0);
const stale=await begin('Stale',1);sql.prepare('UPDATE lake_workbooks SET created=1 WHERE id=?').run(stale.id);await begin('Sweeper',1);assert.equal(sql.prepare('SELECT COUNT(*) n FROM lake_workbooks WHERE id=?').get(stale.id).n,0,'stale staging import swept');
console.log('PASS staged import of a 3-sheet workbook with names and order, rejection of bad sheets, no false completion, abort cleanup, and stale staging sweep.');

// Revision-checked saves across sheets; feeds serve only the published revision.
const bytesBefore=sql.prepare('SELECT bytes FROM lake_workbooks WHERE id=?').get(wb.id).bytes;
res=await api.POST(request({action:'token',sheet:summary.id}));const grant=await res.json();assert.equal(sql.prepare('SELECT hash FROM lake_tokens WHERE id=?').get(grant.id).hash.includes(grant.token),false);
assert.equal((await feed.GET(new Request('https://test/api/data-lake/feed/'+summary.id),{params:Promise.resolve({id:summary.id})})).status,401);assert.equal((await fetchFeed(regions.id,grant.token)).status,403,'credential is scoped to one worksheet');
res=await fetchFeed(summary.id,grant.token);assert.equal(res.status,200);assert.match(await res.text(),/'=CMD/);
const edited={columns:sheetA.columns,rows:[['Updated painting',42]]};res=await api.POST(request({action:'update',id:wb.id,sheet:summary.id,revision:committed.revision,data:edited}));assert.equal(res.status,200,await res.clone().text());const rev2=(await res.json()).revision;assert.notEqual(rev2,committed.revision);
assert.match(await(await fetchFeed(summary.id,grant.token)).text(),/Updated painting/);
assert.equal((await api.POST(request({action:'update',id:wb.id,sheet:regions.id,revision:committed.revision,data:sheetB}))).status,409,'a second session with the old revision is rejected');
assert.equal(JSON.stringify((await(await get('sheet='+regions.id)).json()).data),JSON.stringify(sheetB),'losing session changed nothing');
res=await api.POST(request({action:'update',id:wb.id,sheet:regions.id,revision:rev2,data:{columns:['Region','Sales'],rows:[['South',5]]}}));assert.equal(res.status,200);const rev3=(await res.json()).revision;
list=await(await get()).json();assert.equal(list.workbooks.find(w=>w.id===wb.id).revision,rev3);assert.deepEqual((await(await get('sheet='+summary.id)).json()).data,edited);assert.deepEqual((await(await get('sheet='+regions.id)).json()).data.rows,[['South',5]]);
assert.equal(sql.prepare('SELECT SUM(bytes) b FROM lake_sheets WHERE workbook=?').get(wb.id).b,sql.prepare('SELECT bytes FROM lake_workbooks WHERE id=?').get(wb.id).bytes,'workbook budget tracks sheet sizes');assert.notEqual(bytesBefore,sql.prepare('SELECT bytes FROM lake_workbooks WHERE id=?').get(wb.id).bytes);
assert.equal((await api.POST(request({action:'update',id:wb.id,sheet:summary.id,revision:rev3,data:{columns:['a'],rows:[[1,2]]}}))).status,400);
assert.equal((await api.POST(request({action:'update',id:wb.id,sheet:legacyId,revision:rev3,data:sheetA}))).status,404,'sheet must belong to the workbook');
sql.exec("UPDATE members SET status='removed'");assert.equal((await fetchFeed(summary.id,grant.token)).status,403);sql.exec("UPDATE members SET status='active'");sql.prepare('UPDATE lake_tokens SET expires=0 WHERE id=?').run(grant.id);assert.equal((await fetchFeed(summary.id,grant.token)).status,403);sql.prepare('UPDATE lake_tokens SET expires=9999999999999 WHERE id=?').run(grant.id);await api.POST(request({action:'revoke',id:grant.id}));assert.equal((await fetchFeed(summary.id,grant.token)).status,403);
const ctx={importScripts(){},initSqlJs:()=>initSqlJs({wasmBinary:fs.readFileSync("public/lake/sql-wasm.wasm")}),postMessage(d){ctx.result=d},onmessage:null};vm.createContext(ctx);vm.runInContext(fs.readFileSync('public/lake/query-worker.js','utf8'),ctx);await ctx.onmessage({data:{dataset:sheetA,sql:'SELECT SUM(Quantity) AS total FROM dataset'}});assert.equal(ctx.result.rows[0][0],4);await ctx.onmessage({data:{dataset:sheetA,sql:'SELECT * FROM members'}});assert.match(ctx.result.error,/no such table/);await ctx.onmessage({data:{dataset:sheetA,action:'change',sql:'DELETE FROM dataset'}});assert.equal(ctx.result.dataset.rows.length,0);await ctx.onmessage({data:{dataset:sheetA,action:'export'}});const SQL=await initSqlJs();const db=new SQL.Database(ctx.result.bytes);assert.equal(db.exec('SELECT COUNT(*) FROM dataset')[0].values[0][0],2);db.close();
console.log('PASS scoped hashed credentials, published-revision feeds, per-sheet revision-checked saves, concurrent conflict rejection, reload after save, budget tracking, expiry, revocation, SQL isolation and SQLite export.');

// Deleting a workbook removes every worksheet, object and credential, then a fresh upload works again.
const keep=await begin('Keep me',1);await api.POST(request({action:'import-sheet',workbook:keep.id,position:0,name:'Only',data:sheetA}));await api.POST(request({action:'import-commit',workbook:keep.id}));
const nextGrant=await(await api.POST(request({action:'token',sheet:regions.id}))).json();objects.set('data-lake/'+wb.id+'/'+summary.id+'/old-revision','old data');
for(const denied of [null,'member','admin']){role=denied;assert.equal((await api.POST(request({action:'delete',id:wb.id}))).status,denied===null?401:403)}role='owner';
assert.equal((await api.POST(request({action:'delete',id:wb.id},'https://evil'))).status,403);assert.equal((await api.POST(request({action:'delete',id:'../private-integrations'}))).status,400);
assert.equal((await api.POST(request({action:'delete',id:wb.id}))).status,200);
assert.equal((await get('sheet='+summary.id)).status,404);assert.equal((await fetchFeed(regions.id,nextGrant.token)).status,403);
assert.equal(sql.prepare('SELECT COUNT(*) n FROM lake_sheets WHERE workbook=?').get(wb.id).n,0);assert.equal(sql.prepare('SELECT COUNT(*) n FROM lake_tokens WHERE dataset IN (?,?)').get(summary.id,regions.id).n,0);assert.equal([...objects.keys()].filter(k=>k.startsWith('data-lake/'+wb.id)).length,0);
assert.equal((await get('sheet='+keep.id)).status,404);list=await(await get()).json();assert.deepEqual(list.workbooks.map(w=>w.name).sort(),['Keep me','Legacy']);
assert.equal((await api.POST(request({action:'delete',id:wb.id}))).status,200,'safe retry');assert.equal((await api.POST(request({action:'update',id:wb.id,sheet:summary.id,revision:rev3,data:sheetA}))).status,404);
assert.equal((await api.POST(request({action:'delete',id:legacyId}))).status,200);assert.equal(objects.has('data-lake/'+legacyId),false);assert.equal(sql.prepare('SELECT COUNT(*) n FROM lake_datasets').get().n,0,'legacy row removed with its workbook');
const again=await begin('Sales book',1);await api.POST(request({action:'import-sheet',workbook:again.id,position:0,name:'Summary',data:sheetA}));assert.equal((await api.POST(request({action:'import-commit',workbook:again.id}))).status,200);
console.log('PASS owner-only deletion of whole workbooks, all revisions and credentials removed, other workbooks preserved, safe retries, legacy cleanup and re-upload.');
