import fs from 'node:fs';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import ts from 'typescript';import vm from 'node:vm';import initSqlJs from 'sql.js';
const sql=new DatabaseSync(':memory:');sql.exec("CREATE TABLE members(id TEXT PRIMARY KEY,role TEXT,status TEXT)");sql.exec(fs.readFileSync('drizzle/0015_safe_skin.sql','utf8'));sql.exec("INSERT INTO members VALUES('owner','owner','active')");
const objects=new Map();let role='owner';const runtime={database:()=>({async batch(statements){sql.exec('BEGIN');try{const result=await Promise.all(statements.map(s=>s.run()));sql.exec('COMMIT');return result}catch(e){sql.exec('ROLLBACK');throw e}},prepare(q){let args=[];return {bind(...v){args=v;return this},async first(){return sql.prepare(q).get(...args)},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {meta:sql.prepare(q).run(...args)}}}}}),bucket:()=>({async put(k,v){objects.set(k,v)},async get(k){return objects.has(k)?{json:async()=>JSON.parse(objects.get(k))}:null},async delete(k){for(const key of Array.isArray(k)?k:[k])objects.delete(key)},async list({prefix,cursor}){const keys=[...objects.keys()].filter(k=>k.startsWith(prefix)&&(!cursor||k>cursor)).sort();return {objects:keys.slice(0,1).map(key=>({key})),truncated:keys.length>1,cursor:keys[0]}}}),workspaceAccess:async()=>role===null?{response:Response.json({}, {status:401})}:{member:{id:'owner',role}}};globalThis.lakeTest=runtime;
async function load(path,names){const src=fs.readFileSync(path,'utf8').replace(/^import .*;\s*$/gm,'');const code='const {'+names.join(',')+'}=globalThis.lakeTest;\n'+src;return import('data:text/javascript;base64,'+Buffer.from(ts.transpileModule(code,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText).toString('base64'))}
Object.assign(runtime,await load('lib/data-lake.ts',['database','bucket','workspaceAccess']));const api=await load('app/api/data-lake/route.ts',['database','bucket','lakeOwner','lakeJson','audit','validateData','readData','hashToken']);const feed=await load('app/api/data-lake/feed/[id]/route.ts',['database','lakeJson','hashToken','readData','csv','audit']);
const request=(d,origin='https://test')=>new Request('https://test/api/data-lake',{method:'POST',headers:{origin},body:JSON.stringify(d)});for(const r of [null,'member','admin']){role=r;assert.equal((await api.GET(new Request('https://test/api/data-lake'))).status,r===null?401:403);assert.equal((await api.POST(request({action:'upload'}))).status,r===null?401:403)}role='owner';assert.equal((await api.POST(request({},'https://evil'))).status,403);
const dataset={columns:['Item','Quantity'],rows:[['Painting',3],['=CMD()',1]]};let res=await api.POST(request({action:'upload',name:'Test',data:dataset}));assert.equal(res.status,200);const {id}=await res.json();assert.equal(objects.size,1);assert.equal((await api.POST(request({action:'upload',name:'Bad',data:{columns:['a','A'],rows:[]}}))).status,400);
res=await api.POST(request({action:'token',id}));const grant=await res.json();assert.equal(sql.prepare('SELECT hash FROM lake_tokens').get().hash.includes(grant.token),false);
const fetchFeed=(dataset=id,token=grant.token)=>feed.GET(new Request('https://test/api/data-lake/feed?dataset='+dataset,{headers:{Authorization:'Basic '+btoa('datalake:'+token)}}),{params:Promise.resolve({id:dataset})});assert.equal((await feed.GET(new Request('https://test/api/data-lake/feed?dataset='+id),{params:Promise.resolve({id})})).status,401);assert.equal((await fetchFeed('other')).status,403);res=await fetchFeed();assert.equal(res.status,200);assert.match(await res.text(),/'=CMD/);const before=sql.prepare('SELECT object_key FROM lake_datasets WHERE id=?').get(id).object_key;const updated={columns:dataset.columns,rows:[['Updated painting',42]]};const saved=await api.POST(request({action:'update',id,revision:before,data:updated}));assert.equal(saved.status,200,await saved.clone().text());assert.match(await(await fetchFeed()).text(),/Updated painting/);assert.match(await(await fetchFeed()).text(),/42/);assert.equal((await api.POST(request({action:'update',id,revision:before,data:dataset}))).status,409,'stale save rejected');assert.deepEqual((await(await api.GET(new Request('https://test/api/data-lake?id='+id))).json()).data,updated);sql.exec("UPDATE members SET status='removed'");assert.equal((await fetchFeed()).status,403);sql.exec("UPDATE members SET status='active'");sql.exec('UPDATE lake_tokens SET expires=0');assert.equal((await fetchFeed()).status,403);sql.exec('UPDATE lake_tokens SET expires=9999999999999');await api.POST(request({action:'revoke',id:grant.id}));assert.equal((await fetchFeed()).status,403);
const ctx={importScripts(){},initSqlJs:()=>initSqlJs({wasmBinary:fs.readFileSync("public/lake/sql-wasm.wasm")}),postMessage(d){ctx.result=d},onmessage:null};vm.createContext(ctx);vm.runInContext(fs.readFileSync('public/lake/query-worker.js','utf8'),ctx);await ctx.onmessage({data:{dataset,sql:'SELECT SUM(Quantity) AS total FROM dataset'}});assert.equal(ctx.result.rows[0][0],4);await ctx.onmessage({data:{dataset,sql:'SELECT * FROM members'}});assert.match(ctx.result.error,/no such table/);await ctx.onmessage({data:{dataset,sql:'DELETE FROM dataset'}});assert.match(ctx.result.error,/SELECT/);await ctx.onmessage({data:{dataset,action:'change',sql:'UPDATE dataset SET Quantity = 9 WHERE Item = \'Painting\''}});assert.equal(ctx.result.dataset.rows[0][1],9);await ctx.onmessage({data:{dataset,action:'change',sql:'DELETE FROM dataset'}});assert.equal(ctx.result.dataset.rows.length,0);await ctx.onmessage({data:{dataset,action:'change',sql:'DROP TABLE dataset'}});assert.match(ctx.result.error,/Use UPDATE/);await ctx.onmessage({data:{dataset,action:'export'}});const SQL=await initSqlJs();const db=new SQL.Database(ctx.result.bytes);assert.equal(db.exec('SELECT COUNT(*) FROM dataset')[0].values[0][0],2);db.close();console.log('PASS owner-only access, CSRF, import validation, scoped/hashed credentials, expiry, revocation, removed owner, CSV formula escaping, SQL isolation and SQLite export.');

const other=await(await api.POST(request({action:'upload',name:'Keep me',data:dataset}))).json();
const nextGrant=await(await api.POST(request({action:'token',id}))).json();
objects.set('data-lake/'+id+'/old-revision','old data');objects.set('data-lake/'+id+'/second-revision','older data');
for(const denied of [null,'member','admin']){role=denied;assert.equal((await api.POST(request({action:'delete',id}))).status,denied===null?401:403)}role='owner';
assert.equal((await api.POST(request({action:'delete',id},'https://evil'))).status,403);
assert.equal((await api.POST(request({action:'delete',id:'../private-integrations'}))).status,400);
assert.equal((await api.POST(request({action:'delete',id}))).status,200);
assert.equal((await api.GET(new Request('https://test/api/data-lake?id='+id))).status,404);
assert.equal((await fetchFeed(id,nextGrant.token)).status,403);
assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM lake_tokens WHERE dataset=?').get(id).n,0);
assert.equal([...objects.keys()].filter(k=>k==='data-lake/'+id||k.startsWith('data-lake/'+id+'/')).length,0);
assert.equal((await api.GET(new Request('https://test/api/data-lake?id='+other.id))).status,200);
assert.equal((await api.POST(request({action:'delete',id}))).status,200,'safe retry');
assert.equal((await api.POST(request({action:'update',id,revision:before,data:dataset}))).status,404);
console.log('PASS owner-only deletion, all stored revisions removed, credentials revoked, other workbook preserved, safe retries and stale-save rejection.');
