import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';import assert from 'node:assert/strict';import ts from 'typescript';import vm from 'node:vm';
const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));
const db={async batch(statements){return Promise.all(statements.map(s=>s.run()))},prepare(q){let values=[];return {bind(...v){values=v;return this},async all(){return {results:sql.prepare(q).all(...values)}},async first(){return sql.prepare(q).get(...values)||null},async run(){return {meta:sql.prepare(q).run(...values)}}}}};
let authMember={id:'owner-test',status:'active',role:'owner',permissions:'{}'};let authStatus=200,allowed=true;const env={WIX_ORDER_SECRETS:JSON.stringify({'faa072bb-65e2-4eeb-95d8-6d5b668a8282':'test-order-connection-secret-at-least-32-bytes'}),WIX_ORDERS_ENABLED_SITES:'[]'};
const modules={'cloudflare:workers':{env},'@/lib/storage':{database:()=>db},'@/lib/access':{workspaceAccess:async permission=>authStatus!==200?{response:Response.json({}, {status:authStatus})}:permission==='viewOrders'&&!allowed?{response:Response.json({}, {status:403})}:{member:authMember}}};
function compile(file){const context={exports:{},Response,Request,URL,console,crypto,TextEncoder,Uint8Array,require:n=>{if(!modules[n])throw Error(n);return modules[n]}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,context);return context.exports;}
modules['@/lib/permissions']=compile('lib/permissions.ts');modules['@/lib/order-analytics']=compile('lib/order-analytics.ts');modules['@/lib/wix-sites']=compile('lib/wix-sites.ts');modules['@/lib/website-orders']=compile('lib/website-orders.ts');const incoming=compile('app/api/orders/receive/route.ts'),api=compile('app/api/orders/route.ts');
const order={siteId:'faa072bb-65e2-4eeb-95d8-6d5b668a8282',token:'test-order-connection-secret-at-least-32-bytes',id:'order-test-1',orderNumber:'123',createdDate:'2026-09-14T12:00:00Z',buyerEmail:'customer@example.com',billingInfo:{contactDetails:{firstName:'Test',lastName:'Customer'}},currency:'CAD',priceSummary:{total:{value:'120.50'}},lineItems:[{itemName:'Art print',sku:'ART-1',quantity:2,descriptionLines:[{name:'Size',description:'Large'}]}],status:'APPROVED',paymentStatus:'PAID',fulfillmentStatus:'NOT_FULFILLED',payments:[{creditCardLastDigits:'1111'}]};
const post=d=>incoming.POST(new Request('https://test/api/orders/receive',{method:'POST',body:JSON.stringify(d)}));
assert.equal((await post({...order,token:'bad'})).status,401);assert.equal((await post({...order,siteId:'unknown'})).status,401);assert.equal((await post({...order,id:''})).status,400);assert.equal((await post(order)).status,200);assert.equal((await post(order)).status,200);assert.equal(sql.prepare('SELECT COUNT(*) n FROM website_orders').get().n,1);
assert.equal((await post({siteId:order.siteId,token:order.token,orders:[{...order,id:'batch-1'},{...order,id:''}]})).status,400);assert.equal(sql.prepare('SELECT COUNT(*) n FROM website_orders').get().n,1);
assert.equal((await post({siteId:order.siteId,token:'bad',orders:[order]})).status,401);
assert.equal((await post({siteId:order.siteId,token:order.token,orders:[order,order]})).status,200);assert.equal(sql.prepare('SELECT COUNT(*) n FROM website_orders').get().n,1);
let r=await api.GET(new Request('https://test/api/orders'));assert.equal(r.status,200);assert.match(r.headers.get('cache-control'),/private, no-store/);const row=(await r.json()).orders[0];assert.equal(row.customer,'Test Customer');assert.equal(row.total,'120.50');assert.equal(row.items[0].quantity,2);assert.equal(row.payments,undefined);assert.equal(row.token,undefined);
assert.equal((await (await api.GET(new Request('https://test/api/orders?q=Test'))).json()).orders.length,1);assert.equal((await (await api.GET(new Request('https://test/api/orders?site=other'))).json()).orders.length,0);
allowed=false;assert.equal((await api.GET(new Request('https://test/api/orders'))).status,403);allowed=true;authStatus=401;assert.equal((await api.GET(new Request('https://test/api/orders'))).status,401);authStatus=403;assert.equal((await api.GET(new Request('https://test/api/orders'))).status,403);
console.log('PASS: authenticated website deliveries, duplicate protection, field mapping, no payment credentials stored, order search, site filtering and member permissions.');

authStatus=200;allowed=true;
const analytics=compile('app/api/orders/analytics/route.ts');
const historical=Array.from({length:60},(_,i)=>({...order,id:'history-'+i,createdDate:'2026-08-03T00:00:00Z',priceSummary:{total:{value:'10.00'}}}));
assert.equal((await post({siteId:order.siteId,token:order.token,orders:historical})).status,200);
await post({...order,id:'canceled',status:'CANCELED',priceSummary:{total:{value:'999.00'}}});
await post({...order,id:'usd',currency:'USD',priceSummary:{total:{value:'888.00'}}});
sql.prepare("INSERT INTO order_classifications VALUES (?,?,?,?,?)").run(order.siteId,'history-0','B2B','owner-test',Date.now());
let stats=await (await analytics.GET(new Request('https://test/api/orders/analytics?currency=CAD&group=month'))).json();
assert.equal(stats.summary.orders,62);assert.equal(stats.summary.value,720.5);assert.equal(stats.segments.find(s=>s.segment==='B2B').orders,1);assert.equal(stats.trend.length,2);assert.equal(stats.trend[0].orders,60);
assert.equal((await analytics.GET(new Request('https://test/api/orders/analytics?from=2026-02-30'))).status,400);
stats=await (await analytics.GET(new Request('https://test/api/orders/analytics?currency=USD'))).json();assert.equal(stats.summary.value,888);
stats=await (await analytics.GET(new Request('https://test/api/orders/analytics?currency=CAD&from=2026-09-01&to=2026-09-14&group=week'))).json();assert.equal(stats.summary.orders,2);assert.equal(stats.trend[0].period,'2026-09-14');
allowed=false;assert.equal((await analytics.GET(new Request('https://test/api/orders/analytics'))).status,403);
const filled=modules['@/lib/order-analytics'].fillPeriods([{period:'2025-12-01',orders:1,value:1},{period:'2026-02-01',orders:1,value:1}],'month');assert.equal(filled.length,3);assert.equal(filled[1].orders,0);
console.log('PASS: analytics includes more than one page, separates currencies, excludes canceled values, respects dates and permissions, and fills missing periods.');

allowed=true;const classify=compile('app/api/orders/classification/route.ts');
const classification=d=>classify.POST(new Request('https://test/api/orders/classification',{method:'POST',body:JSON.stringify(d)}));
assert.equal((await classification({siteId:order.siteId,orderId:order.id,segment:'B2C'})).status,200);
assert.equal(sql.prepare('SELECT segment FROM order_classifications WHERE order_id=?').get(order.id).segment,'B2C');
assert.equal((await classification({siteId:order.siteId,orderId:order.id,segment:'Invalid'})).status,400);
authMember={...authMember,role:'member',permissions:JSON.stringify({viewAnalytics:false})};
assert.equal((await analytics.GET(new Request('https://test/api/orders/analytics'))).status,403);
assert.equal((await classification({siteId:order.siteId,orderId:order.id,segment:'B2B'})).status,403);
console.log('PASS: classification saves and restricts writes to admins, and Analytics respects analytics permissions.');
await post({...order,id:'refresh-test',updatedDate:'2026-09-14T12:01:00Z'});
await post({siteId:order.siteId,token:order.token,importHistory:true,orders:[{...order,id:'refresh-test',updatedDate:'2026-09-14T12:02:00Z',fulfillmentStatus:'FULFILLED'}]});
assert.equal(sql.prepare('SELECT fulfillment FROM website_orders WHERE order_id=?').get('refresh-test').fulfillment,'FULFILLED');
await post({siteId:order.siteId,token:order.token,importHistory:true,orders:[{...order,id:'refresh-test',updatedDate:'2026-09-14T12:01:00Z'}]});
assert.equal(sql.prepare('SELECT fulfillment FROM website_orders WHERE order_id=?').get('refresh-test').fulfillment,'FULFILLED');
assert.equal((await post({siteId:order.siteId,token:'wrong',verifyBefore:'2026-09-15T00:00:00Z'})).status,401);
const verified=await (await post({siteId:order.siteId,token:order.token,verifyBefore:'2026-09-15T00:00:00Z'})).json();assert.equal(verified.totals.find(r=>r.currency==='CAD').orders,63);
console.log('PASS: historical reconciliation updates statuses, rejects stale changes, and protects verification totals.');
