'use client';
import {useCallback,useEffect,useState} from 'react';
import {Plus,ShieldCheck,Search} from 'lucide-react';
import PermissionsEditor from './permissions-editor';
import {MemberProfile} from './direct-messages';
import {permissionOptions,type Permissions} from '@/lib/permissions';
import {Switch} from '@/components/ui/switch';
import {Skeleton} from '@/components/ui/skeleton';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {toast} from 'sonner';
type Person={id:string;email:string|null;name:string;user_id:string|null;role:'owner'|'admin'|'member';status:'active'|'pending'|'removed';effectivePermissions:Permissions};
type Access={me:Person;members:Person[];requireApproval:boolean};
type Action={action:'remove'|'restore'|'approve';person:Person}|{action:'approval';requireApproval:boolean};
export default function AccessPanel(){
 const [transferPerson,setTransferPerson]=useState<Person|null>(null),[confirmEmail,setConfirmEmail]=useState('');
 const [permissionPerson,setPermissionPerson]=useState<Person|null>(null);
 const [data,setData]=useState<Access|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState('');
 const [adding,setAdding]=useState(false),[email,setEmail]=useState(''),[role,setRole]=useState('member'),[editing,setEditing]=useState<Person|null>(null),[confirm,setConfirm]=useState<Action|null>(null);
 const refresh=useCallback(async(signal?:AbortSignal)=>{try{const r=await fetch('/api/access',{signal});const d=await r.json() as Access & {error?:string};if(!r.ok)throw Error(d.error||'Could not load access');setData(d);setError('')}catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:'Could not load access')}},[]);
 useEffect(()=>{const controller=new AbortController();void refresh(controller.signal);const timer=setInterval(()=>{if(!document.hidden)void refresh(controller.signal)},10000);return()=>{controller.abort();clearInterval(timer)}},[refresh]);
 async function change(body:Record<string,unknown>){if(busy)return;setBusy(true);try{const r=await fetch('/api/access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'Could not update access');setAdding(false);setEditing(null);setConfirm(null);setEmail('');if(body.action==='transferOwnership'){window.location.reload();return}toast.success(body.action==='add'?'Access added. Share the workspace link with this person.':'Workspace access updated');await refresh()}catch(e){toast.error(e instanceof Error?e.message:'Could not update access')}finally{setBusy(false)}}
 const owner=data?.me.role==='owner';const canManage=!!data&&data.me.effectivePermissions.manageMembers;
 const people=data?.members.filter(p=>`${p.name} ${p.email} ${p.role} ${p.status}`.toLowerCase().includes(query.toLowerCase()))||[];
 function roles(){return <Select value={role} onValueChange={setRole}><SelectTrigger aria-label="Workspace role"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="member">Member</SelectItem>{owner&&<SelectItem value="admin">Admin</SelectItem>}</SelectContent></Select>}
 return <div className="tool-card access-panel"><div className="tool-title"><h2>Workspace access</h2>{canManage&&<button className="solid-button" disabled={busy} onClick={()=>{setRole('member');setAdding(true)}}><Plus size={16}/>Add person</button>}</div><p>Manage who can use RA Studio’s conversations and files.</p>{error?<div className="error-banner" role="alert">{error}<button onClick={()=>void refresh()}>Try again</button></div>:!data?<Skeleton className="mt-5 h-32 w-full"/>:!canManage?<p className="access-help">Your account cannot manage members. Ask the owner to change your permissions.</p>:<>
 <div className="access-permissions"><ShieldCheck size={20}/><p><strong>{owner?'You are the owner.':'You can manage members.'}</strong> {owner?'You can manage members and admins. You can transfer portal ownership to an active member who has signed in.':'You can add, approve, and remove members. Only the owner can manage admins and assign permissions.'}</p></div>
 <div className="setting-row"><label htmlFor="require-approval"><strong>Approve new members</strong><span>{data.requireApproval?'New people must be approved before seeing chats or files. People you add can enter immediately.':'New people who sign in can join as members. Turn on to require approval.'} Existing members keep their access.</span></label><Switch id="require-approval" checked={data.requireApproval} disabled={!owner||busy} onCheckedChange={v=>setConfirm({action:'approval',requireApproval:v})}/></div>
 <div className="access-list-header"><h3>Current members <span>{data.members.filter(p=>p.status==='active').length}</span></h3><label className="access-search"><Search size={16}/><input placeholder="Find a person" aria-label="Find a person" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 <div className="people-list">{people.map(p=>{const editable=p.role!=='owner'&&p.id!==data.me.id&&(owner||(p.role==='member'&&!p.effectivePermissions.manageMembers));return <div className="person-row" key={p.id}><MemberProfile name={p.name} memberId={p.id} self={p.id===data.me.id} avatar/><div className="person-info"><MemberProfile name={p.name} memberId={p.id} self={p.id===data.me.id}/><span>{p.email||'Existing chat participant'}</span><small>{p.status==='pending'?'Awaiting approval':p.status==='removed'?'Access removed':!p.user_id?'Added · Has not signed in':'Active'}</small></div><span className={'role-badge role-'+p.role}>{p.role}</span>{editable?<div className="member-actions">{owner&&<button className="outline-button" disabled={busy} onClick={()=>setPermissionPerson(p)}>Permissions</button>}{owner&&p.status==='active'&&<button className="outline-button" disabled={busy||!p.user_id||!p.email} title={!p.user_id?'This member must sign in before ownership can be transferred.':undefined} onClick={()=>{setTransferPerson(p);setConfirmEmail('')}}>Transfer portal ownership</button>}{p.status==='pending'&&<button className="outline-button" disabled={busy} onClick={()=>setConfirm({action:'approve',person:p})}>Approve access</button>}{p.status==='removed'?<button className="outline-button" disabled={busy} onClick={()=>setConfirm({action:'restore',person:p})}>Restore access</button>:<>{owner&&p.status==='active'&&<button className="outline-button" disabled={busy} onClick={()=>{setEditing(p);setRole(p.role==='member'?'admin':'member')}}>{p.role==='member'?'Promote to admin':'Demote to member'}</button>}<button className="outline-button remove-member" disabled={busy} onClick={()=>setConfirm({action:'remove',person:p})}>Remove access</button></>}</div>:<span className="protected-access">{p.role==='owner'?'Protected':p.id===data.me.id?'You':'Owner manages'}</span>}</div>})}{!people.length&&<p className="access-help">No people match your search.</p>}</div>
 <p className="access-help">Includes existing chat participants and people added by email. Removing access blocks future chat, analytics, and file requests; their past messages remain. Files already downloaded cannot be recalled.</p><p className="access-help">These roles apply within RA Studio. Site visibility and editor permissions are managed separately in ChatGPT’s Site sharing settings.</p>
 </>}
 <Dialog open={!!transferPerson} onOpenChange={open=>{if(!open&&!busy)setTransferPerson(null)}}><DialogContent><DialogHeader><DialogTitle>Transfer portal ownership</DialogTitle><DialogDescription>{transferPerson?.name} ({transferPerson?.email}) will become the RA Studio owner, including access to Data Lake, member permissions and integrations. You will become an admin and lose owner-only access.</DialogDescription></DialogHeader><form className="dialog-form" onSubmit={e=>{e.preventDefault();if(transferPerson)void change({action:'transferOwnership',id:transferPerson.id,confirmEmail})}}><p><strong>This transfers portal administration only.</strong> ChatGPT Site ownership, code editing and hosting remain with the existing account. Do not close that account until the hosting transfer or migration is complete. Existing Power BI credentials issued by you will stop working; the new owner can create replacements.</p><label>Type the new owner’s email to confirm<input type="email" required autoComplete="off" disabled={busy} value={confirmEmail} onChange={e=>setConfirmEmail(e.target.value)}/></label><div className="scan-actions"><button type="button" className="outline-button" disabled={busy} onClick={()=>setTransferPerson(null)}>Cancel</button><button className="solid-button" disabled={busy||!transferPerson?.email||confirmEmail.trim().toLowerCase()!==transferPerson.email.toLowerCase()}>{busy?'Transferring…':'Confirm ownership transfer'}</button></div></form></DialogContent></Dialog>
 {data&&<details className="my-permissions"><summary>Your assigned permissions</summary><ul>{permissionOptions.map(p=><li key={p.key}>{p.label}: <strong>{data.me.effectivePermissions[p.key]?'Allowed':'Not allowed'}</strong></li>)}</ul></details>}
 {permissionPerson&&<PermissionsEditor key={permissionPerson.id} person={permissionPerson} onClose={()=>setPermissionPerson(null)} onSaved={()=>void refresh()}/>}
 <Dialog open={adding||!!editing} onOpenChange={open=>{if(!open&&!busy){setAdding(false);setEditing(null)}}}><DialogContent><DialogHeader><DialogTitle>{editing?'Edit role':'Add a person'}</DialogTitle><DialogDescription>{editing?`Change the role for ${editing.email||editing.name}. This resets individual permissions to the new role’s defaults.`:'Use the email address they use to sign in to ChatGPT. Adding access does not send an email.'}</DialogDescription></DialogHeader><form className="dialog-form" onSubmit={e=>{e.preventDefault();void change(editing?{action:'role',id:editing.id,role}:{action:'add',email,role})}}>{!editing&&<label>Email address<input type="email" autoFocus required maxLength={254} value={email} disabled={busy} onChange={e=>setEmail(e.target.value)}/></label>}<div><p className="role-label">Role</p>{roles()}</div><p>{role==='admin'?'Admins can manage members and approval requests. Only the owner can change admins.':'Members can chat, upload and download files, and view analytics.'}</p><button className="solid-button" disabled={busy||!!editing&&role===editing.role}>{busy?'Saving…':editing?'Save role':'Add access'}</button></form></DialogContent></Dialog>
 <AlertDialog open={!!confirm} onOpenChange={open=>{if(!open&&!busy)setConfirm(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{confirm?.action==='approval'?(confirm.requireApproval?'Require approval for new people?':'Allow new people to join?'):confirm?.action==='remove'?'Remove workspace access?':confirm?.action==='restore'?'Restore workspace access?':'Approve workspace access?'}</AlertDialogTitle><AlertDialogDescription>{confirm?.action==='approval'?(confirm.requireApproval?'New sign-ins will wait for an owner or admin to approve access. Existing members keep access.':'New people who can open the Site and sign in will join as members. People already pending or removed still need individual approval or restoration.'):confirm?`${confirm.person.email||confirm.person.name} ${confirm.action==='remove'?'will lose access to conversations and files. Past messages will remain.':'will be able to use RA Studio as a member.'}`:''}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><AlertDialogAction className={confirm?.action==='remove'?'delete-button':''} disabled={busy} onClick={e=>{e.preventDefault();if(confirm)void change(confirm.action==='approval'?{action:'approval',requireApproval:confirm.requireApproval}:{action:confirm.action,id:confirm.person.id})}}>{busy?'Saving…':'Confirm'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>
}
