'use client';
import {memo,useEffect,useState,useRef,useCallback} from 'react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import type {LakeData} from '@/lib/data-lake';
type SheetMeta={id:string;workbook:string;position:number;name:string;row_count:number;updated:number};
type WorkbookMeta={id:string;name:string;revision:string;sheet_count:number;bytes:number;created:number;updated:number;sheets:SheetMeta[]};
type Parsed={sheets:{name:string;data:LakeData;bytes:number;notes:string[]}[];failed:{name:string;error:string}[];skipped:string[];totalBytes:number};
type Loaded=Record<string,{data:LakeData;dirty:boolean}>;
async function response(r:Response){const d:any=await r.json();if(!r.ok)throw Error(d.error||'Request failed.');return d}
const post=(d:unknown,signal?:AbortSignal)=>fetch('/api/data-lake',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d),signal}).then(response);
function download(bytes:BlobPart,name:string,type:string){const url=URL.createObjectURL(new Blob([bytes],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const safeName=(s:string)=>s.replace(/[^\w.-]+/g,'_').slice(0,80)||'workbook';
export default memo(DataLake);
function DataLake(){
 const [tab,setTab]=useState('sheets'),[workbooks,setWorkbooks]=useState<WorkbookMeta[]>([]),[tokens,setTokens]=useState<any[]>([]),[audit,setAudit]=useState<any[]>([]),[ready,setReady]=useState(false);
 const [selected,setSelected]=useState(''),[revision,setRevision]=useState(''),[active,setActive]=useState(''),[loaded,setLoaded]=useState<Loaded>({}),[loading,setLoading]=useState('');
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[processing,setProcessing]=useState(false),[progress,setProgress]=useState(''),[resetting,setResetting]=useState(false);
 const [sourceFile,setSourceFile]=useState<File|null>(null),[parsed,setParsed]=useState<Parsed|null>(null);
 const [rowStart,setRowStart]=useState(0),[columnStart,setColumnStart]=useState(0),[sql,setSql]=useState('SELECT * FROM dataset LIMIT 100'),[result,setResult]=useState<any>(null),[proposed,setProposed]=useState<LakeData|null>(null),[secret,setSecret]=useState('');
 const cancelTask=useRef<(()=>void)|null>(null),worker=useRef<Worker|null>(null),timeout=useRef<ReturnType<typeof setTimeout>|null>(null),resetLock=useRef(false);
 const workbook=workbooks.find(w=>w.id===selected)||null,sheets=workbook?.sheets||[],sheet=sheets.find(s=>s.id===active)||null,current=active?loaded[active]:undefined,data=current?.data||null;
 const dirtyCount=Object.values(loaded).filter(s=>s.dirty).length,dirty=dirtyCount>0;
 const refresh=useCallback(async()=>{const d=await fetch('/api/data-lake',{cache:'no-store'}).then(response);setWorkbooks(d.workbooks);setTokens(d.tokens);setAudit(d.audit);setReady(true);return d.workbooks as WorkbookMeta[]},[]);
 useEffect(()=>{refresh().catch(e=>setError(e.message));return()=>{worker.current?.terminate();if(timeout.current)clearTimeout(timeout.current)}},[refresh]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
 // Worksheets load on demand and stay cached with their edits, so switching tabs never loses work.
 useEffect(()=>{if(!active||loaded[active]||!selected)return;const c=new AbortController();setLoading(active);setError('');fetch('/api/data-lake?sheet='+encodeURIComponent(active),{signal:c.signal,cache:'no-store'}).then(response).then(d=>{if(c.signal.aborted)return;setLoaded(old=>({...old,[active]:{data:d.data,dirty:false}}));if(d.workbook?.revision)setRevision(d.workbook.revision)}).catch(e=>{if(!c.signal.aborted)setError(e.message)}).finally(()=>{if(!c.signal.aborted)setLoading('')});return()=>c.abort()},[active,selected,loaded]);
 function openWorkbook(id:string){setSelected(id);setLoaded({});setRevision(workbooks.find(w=>w.id===id)?.revision||'');setActive(workbooks.find(w=>w.id===id)?.sheets[0]?.id||'');setRowStart(0);setColumnStart(0);setProposed(null);setResult(null);setSecret('')}
 function fileTask(message:any,onProgress?:(p:any)=>void):Promise<any>{setProcessing(true);return new Promise((resolve,reject)=>{const w=new Worker('/lake/file-worker.js?v=3');worker.current=w;const stop=()=>{w.terminate();if(timeout.current)clearTimeout(timeout.current);cancelTask.current=null;setProcessing(false);setProgress('')};const arm=()=>{if(timeout.current)clearTimeout(timeout.current);timeout.current=setTimeout(()=>{stop();reject(Error('File processing stalled for 60 seconds. Split the file and try again.'))},60000)};cancelTask.current=()=>{stop();reject(Error('File operation cancelled. Your saved data is unchanged.'))};arm();w.onmessage=({data:d})=>{if(d.progress){arm();onProgress?.(d.progress);return}stop();d.error?reject(Error(d.error)):resolve(d)};w.onerror=()=>{stop();reject(Error('File processor could not start. Reload and try again.'))};w.postMessage(message,message.bytes?[message.bytes]:[])})}
 async function upload(file:File){setError('');setNotice('');setBusy(true);setParsed(null);setSourceFile(null);try{if(file.size>5*1024*1024)throw Error('Choose a file under 5 MB.');const d:Parsed=await fileTask({action:'import',name:file.name,bytes:await file.arrayBuffer()},p=>setProgress('Reading worksheet '+(p.index+1)+' of '+p.count+': '+p.name));setSourceFile(file);setParsed(d)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 // Staged import: begin → one request per worksheet → commit. Any failure aborts so nothing half-imported is ever listed.
 async function saveWorkbook(){if(!parsed||!sourceFile||!parsed.sheets.length)return;if(dirty&&!window.confirm('Discard unsaved edits and open the new workbook?'))return;setBusy(true);setError('');setProcessing(true);const c=new AbortController();cancelTask.current=()=>c.abort();let id='';try{const name=sourceFile.name.replace(/\.(xlsx|csv)$/i,'');id=(await post({action:'import-begin',name,sheetCount:parsed.sheets.length},c.signal)).id;for(let i=0;i<parsed.sheets.length;i++){const s=parsed.sheets[i];setProgress('Saving worksheet '+(i+1)+' of '+parsed.sheets.length+': '+s.name);await post({action:'import-sheet',workbook:id,position:i,name:s.name,data:s.data},c.signal)}setProgress('Finishing…');const done=await post({action:'import-commit',workbook:id},c.signal);const list=await refresh();setParsed(null);setSourceFile(null);setLoaded({});setSelected(done.id);setRevision(done.revision);setActive(list.find(w=>w.id===done.id)?.sheets[0]?.id||'');const skipped=[...parsed.failed.map(f=>f.name),...parsed.skipped];setNotice('Workbook saved with '+parsed.sheets.length+' worksheet'+(parsed.sheets.length===1?'':'s')+'.'+(skipped.length?' Not included: '+skipped.join(', ')+'.':''))}catch(e){if(id){try{await post({action:'import-abort',workbook:id})}catch{}}setError(c.signal.aborted?'Import cancelled. Nothing was saved.':(e as Error).message)}finally{cancelTask.current=null;setProcessing(false);setProgress('');setBusy(false)}}
 async function saveChanges(){if(!workbook)return;setBusy(true);setError('');let rev=revision;try{for(const s of sheets){const item=loaded[s.id];if(!item?.dirty)continue;const d=await post({action:'update',id:workbook.id,sheet:s.id,revision:rev,data:item.data});rev=d.revision;setRevision(rev);setLoaded(old=>({...old,[s.id]:{data:item.data,dirty:false}}))}setNotice('Saved. SQL, exports and connected Power BI / Excel refreshes now use this version.');await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function resetWorkbook(){if(resetLock.current||(busy&&!processing))return;resetLock.current=true;setResetting(true);const deleted=selected;
 try{cancelTask.current?.();await Promise.resolve();setProcessing(false);setBusy(true);setError('');setNotice('Deleting workbook…');
  if(deleted){const r=await fetch('/api/data-lake',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'delete',id:deleted}),signal:AbortSignal.timeout(30000)});await response(r);}
  setWorkbooks(old=>old.filter(w=>w.id!==deleted));setTokens(old=>old.filter(t=>!workbook?.sheets.some(s=>s.id===t.dataset)));setSelected('');setActive('');setLoaded({});setRevision('');setParsed(null);setSourceFile(null);setProposed(null);setResult(null);setSql('SELECT * FROM dataset LIMIT 100');setRowStart(0);setColumnStart(0);setSecret('');setNotice(deleted?'Workbook deleted. Import a new file to start again.':'Import cleared. Choose a file to start again.');
 }catch(e){setNotice('');setError(e instanceof Error&&e.name==='TimeoutError'?'Deletion timed out. Click Reset workbook again to safely retry.':e instanceof Error?e.message:'Could not delete workbook. Try again.')}finally{setBusy(false);setResetting(false);resetLock.current=false}}
 function setSheetData(next:LakeData){if(!active)return;setLoaded(old=>({...old,[active]:{data:next,dirty:true}}));setResult(null);setProposed(null)}
 function editCell(row:number,col:number,text:string){if(!data)return;const rows=[...data.rows],r=[...rows[row]],old=r[col];r[col]=typeof old==='number'&&text.trim()!==''&&Number.isFinite(Number(text))?Number(text):typeof old==='boolean'&&/^(true|false)$/i.test(text)?text.toLowerCase()==='true':text;rows[row]=r;setSheetData({...data,rows})}
 function query(action='query'){if(!data)return;setProposed(null);setBusy(true);setProcessing(true);setError('');worker.current?.terminate();const w=new Worker('/lake/query-worker.js?v=2');worker.current=w;const stop=()=>{w.terminate();if(timeout.current)clearTimeout(timeout.current);setBusy(false);cancelTask.current=null;setProcessing(false)};cancelTask.current=()=>{stop();setNotice('SQL operation cancelled.')};timeout.current=setTimeout(()=>{stop();setError('Query exceeded 10 seconds. Simplify the query and try again.')},10000);w.onmessage=({data:d})=>{stop();if(d.error)setError(d.error);else if(d.dataset){setProposed(d.dataset);setNotice(d.changed+' rows affected. Review the preview, then apply and save.')}else if(d.bytes)download(d.bytes,safeName(sheet?.name||'sheet')+'.sqlite','application/vnd.sqlite3');else setResult(d)};w.onerror=()=>{stop();setError('SQL workspace could not start.')};w.postMessage({action,dataset:data,sql})}
 async function exportFile(kind:string){if(!workbook||!data)return;if(kind==='sqlite'){query('export');return}setBusy(true);setError('');try{if(kind==='csv'){const d=await fileTask({action:'export',kind,dataset:data});download(d.text,safeName(sheet?.name||'sheet')+'.csv','text/csv');return}
  // The Excel export carries every worksheet, including edits not yet saved, in the original order.
  const all=[];for(const s of sheets){let item=loaded[s.id];if(!item){setProgress('Loading worksheet: '+s.name);const d=await fetch('/api/data-lake?sheet='+encodeURIComponent(s.id),{cache:'no-store'}).then(response);item={data:d.data,dirty:false};setLoaded(old=>({...old,[s.id]:old[s.id]||item}))}all.push({name:s.name,data:item.data})}setProgress('');const d=await fileTask({action:'export',kind:'xlsx',sheets:all});download(d.bytes,safeName(workbook.name)+'.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')}catch(e){setError((e as Error).message)}finally{setProgress('');setBusy(false)}}
 async function token(){if(!active)return;setBusy(true);setError('');try{const d=await post({action:'token',sheet:active});setSecret(d.token);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const url=typeof window==='undefined'||!active?'':window.location.origin+'/api/data-lake/feed/'+encodeURIComponent(active);
 const sheetLabel=(id:string)=>{for(const w of workbooks){const s=w.sheets.find(s=>s.id===id);if(s)return w.name+' · '+s.name}return id};
 const table=(d:LakeData,limit=20)=><div className="orders-table"><table><thead><tr>{d.columns.map((c,i)=><th key={i}>{c}</th>)}</tr></thead><tbody>{d.rows.slice(0,Math.min(limit,Math.max(1,Math.floor(1000/d.columns.length)))).map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v===null?'NULL':String(v)}</td>)}</tr>)}</tbody></table></div>;
 return <section className="workspace-tool orders-workspace"><div className="tool-title"><h1>Data Lake</h1><span className="inventory-stock-label">Owner only · Restricted</span></div><p className="tool-intro">One saved workbook with all its worksheets for sheet editing, SQL, Excel / CSV exports and Power BI refreshes.</p>{notice&&<p role="status" className="order-data-note">{notice}</p>}{error&&<p className="error-banner" role="alert">{error}</p>}{!ready?<p>{error?'Access or storage unavailable.':'Checking access…'}{error&&<button onClick={()=>refresh().catch(e=>setError(e.message))}>Retry</button>}</p>:<><Tabs value={tab} onValueChange={v=>{setTab(v);setSecret('')}}><TabsList><TabsTrigger value="sheets">Sheets</TabsTrigger><TabsTrigger value="sql">SQL workspace</TabsTrigger><TabsTrigger value="connect">Power BI / SQL</TabsTrigger><TabsTrigger value="audit">Access log</TabsTrigger></TabsList></Tabs>
 <div className="order-filters" style={{marginTop:20}}><label>Workbook<select aria-label="Workbook" value={selected} onChange={e=>{if(!dirty||window.confirm('Discard unsaved sheet edits?'))openWorkbook(e.target.value)}} disabled={busy||resetting}><option value="">Choose a workbook</option>{workbooks.map(w=><option key={w.id} value={w.id}>{w.name} · {w.sheet_count} sheet{w.sheet_count===1?'':'s'}</option>)}</select></label>{workbook&&<button className="solid-button" disabled={!dirty||busy} onClick={saveChanges}>{busy?'Working…':dirty?'Save '+dirtyCount+' changed sheet'+(dirtyCount===1?'':'s'):'All changes saved'}</button>}{(selected||sourceFile||parsed||processing||resetting)&&<div><button type="button" className="outline-button" style={{color:'#a12b25',borderColor:'#c96d66'}} disabled={resetting||(busy&&!processing)} onClick={()=>void resetWorkbook()}>{resetting?'Deleting workbook…':selected?'Reset & delete workbook':'Clear import'}</button><small style={{display:'block',marginTop:6}}>{selected?'Permanently deletes every worksheet in the selected workbook and revokes its feed credentials.':'Clears this import.'}</small></div>}</div>
 {workbook&&sheets.length>0&&<div role="tablist" aria-label="Worksheets" className="scan-actions" style={{flexWrap:'wrap',marginTop:12}}>{sheets.map(s=><button key={s.id} role="tab" aria-selected={s.id===active} className={s.id===active?'solid-button':'outline-button'} disabled={busy&&!processing} onClick={()=>{setActive(s.id);setRowStart(0);setColumnStart(0);setResult(null);setProposed(null);setSecret('')}}>{s.name}{loaded[s.id]?.dirty?' •':''}</button>)}</div>}
 {dirty&&<p className="order-data-note">Unsaved edits on {dirtyCount} sheet{dirtyCount===1?'':'s'}. SQL and downloads use your edits; external feeds update after saving.</p>}
 {tab==='sheets'&&<><div className="tool-card"><h2>Import a workbook</h2><p>CSV or .xlsx · 5 MB per file · Every worksheet is imported together and kept in order, up to 25 worksheets and 64 MB of extracted data per workbook. Each worksheet may hold 50,000 populated rows, 100 columns and 7 MB of extracted data. Empty formatting and blank rows are ignored. The first populated row names the columns. Formulas keep their saved results only; styles, charts, merged cells and macros are not imported.</p><input aria-label="Upload CSV or Excel workbook" type="file" accept=".csv,.xlsx" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value=''}}/>
  {parsed&&<><h3>{sourceFile?.name}</h3><ul>{parsed.sheets.map(s=><li key={s.name}><strong>{s.name}</strong> · {s.data.rows.length.toLocaleString()} rows · {s.data.columns.length} columns{s.notes.map((n,i)=><small key={i} style={{display:'block'}}>{n}</small>)}</li>)}{parsed.failed.map(f=><li key={f.name} className="error-banner"><strong>{f.name}</strong> cannot be imported: {f.error}</li>)}{parsed.skipped.map(n=><li key={n}><strong>{n}</strong> · empty, not imported</li>)}</ul>{parsed.sheets.length>0?<><p>{parsed.sheets.length} worksheet{parsed.sheets.length===1?'':'s'} ready.{parsed.failed.length>0&&' The workbook will be saved without the '+parsed.failed.length+' worksheet'+(parsed.failed.length===1?'':'s')+' listed above.'} Preview of {parsed.sheets[0].name}:</p>{table(parsed.sheets[0].data,5)}<button className="solid-button" disabled={busy} onClick={saveWorkbook}>{parsed.failed.length?'Save workbook without failed sheets':'Save workbook'}</button></>:<p className="error-banner">No worksheet could be imported. Fix the sheets listed above and upload again.</p>}</>}</div>
  {workbook&&!data&&<p role="status">{loading?'Loading worksheet…':error?'':'Choose a worksheet.'}</p>}
  {data&&sheet&&<><h2>Edit sheet: {sheet.name}</h2><p>Showing rows {data.rows.length?rowStart+1:0}–{Math.min(rowStart+25,data.rows.length)} of {data.rows.length.toLocaleString()}, columns {columnStart+1}–{Math.min(columnStart+10,data.columns.length)}. All rows remain saved.</p><div className="scan-actions"><button className="outline-button" disabled={rowStart===0} onClick={()=>setRowStart(v=>Math.max(0,v-25))}>Previous rows</button><button className="outline-button" disabled={rowStart+25>=data.rows.length} onClick={()=>setRowStart(v=>v+25)}>Next rows</button><button className="outline-button" disabled={columnStart===0} onClick={()=>setColumnStart(v=>Math.max(0,v-10))}>Previous columns</button><button className="outline-button" disabled={columnStart+10>=data.columns.length} onClick={()=>setColumnStart(v=>v+10)}>Next columns</button></div><p>Click a cell to edit its value. Formula cells import their saved results; this editor does not recalculate Excel formulas.</p><button className="outline-button" disabled={busy||data.rows.length>=50000} onClick={()=>{setSheetData({...data,rows:[data.columns.map(()=>null),...data.rows]});setRowStart(0);setColumnStart(0)}}>Add row</button><div className="orders-table"><table><thead><tr><th>Row</th>{data.columns.slice(columnStart,columnStart+10).map((c,i)=><th key={i}>{c}</th>)}</tr></thead><tbody>{data.rows.slice(rowStart,rowStart+25).map((r,i)=><tr key={i}><td>{rowStart+i+1}</td>{r.slice(columnStart,columnStart+10).map((v,j)=><td key={j}><input aria-label={'Row '+(rowStart+i+1)+', '+data.columns[columnStart+j]} disabled={busy} value={v===null?'':String(v)} onChange={e=>editCell(rowStart+i,columnStart+j,e.target.value)} style={{minWidth:140,padding:8,border:'1px solid #d6ded9',borderRadius:4}}/></td>)}</tr>)}</tbody></table></div><div className="scan-actions"><button className="outline-button" disabled={busy} onClick={()=>exportFile('csv')}>Download this sheet as CSV</button><button className="outline-button" disabled={busy} onClick={()=>exportFile('xlsx')}>Download workbook ({sheets.length} sheet{sheets.length===1?'':'s'}) as Excel</button><button className="outline-button" disabled={busy} onClick={()=>exportFile('sqlite')}>Download this sheet as SQLite</button></div><p><small>Downloads are rebuilt from the saved data, including unsaved edits shown here. Original styles, charts, macros and formula recalculation are not reproduced.</small></p></>}</>}
 {tab==='sql'&&<div className="tool-card"><h2>SQL workspace</h2><p>Query the open worksheet{sheet?' ('+sheet.name+')':''} as <code>dataset</code>. Quote column names with double quotes. Switch worksheets with the tabs above. SELECT reads data; UPDATE, INSERT and DELETE let you preview changes before applying them to the sheet. Save the sheet to update external feeds. Queries return up to 1,000 rows; on-screen previews display at most 1,000 cells to keep the page responsive.</p><textarea aria-label="SQL query" value={sql} onChange={e=>setSql(e.target.value)} rows={5} style={{width:'100%',fontFamily:'monospace',border:'1px solid #aaa',padding:12}}/><button className="solid-button" disabled={!data||busy} onClick={()=>query()}>{busy?'Running…':'Run SELECT'}</button><button className="outline-button" disabled={!data||busy} onClick={()=>query('change')}>Preview SQL changes</button>{proposed&&<><h3>Proposed sheet</h3>{table(proposed)}<button className="solid-button" onClick={()=>{setSheetData(proposed);setRowStart(0);setColumnStart(0);setNotice('Changes applied to the sheet. Click Save to publish them.')}}>Apply to sheet</button><button className="outline-button" onClick={()=>setProposed(null)}>Discard preview</button></>}{result&&<>{result.truncated&&<p>Results limited to the first 1,000 rows.</p>}{table(result,1000)}</>}</div>}
 {tab==='connect'&&<div className="tool-card"><h2>Power BI and Excel connection</h2><p>Connection setup is required in your Microsoft application. This portal has no access to your Microsoft account. Both applications can refresh from the same saved worksheet using its feed.</p><p>Create a read-only credential for the open worksheet{sheet?' ('+sheet.name+')':''}. It expires in 30 days. Anyone holding it can read the last saved version of that worksheet until it expires or you revoke it.</p><button className="solid-button" disabled={!active||busy} onClick={token}>Create worksheet credential</button>{secret&&<div role="status"><p>Copy now. This credential will not be shown again.</p><input aria-label="New worksheet credential" type="password" readOnly value={secret}/><button className="outline-button" onClick={()=>navigator.clipboard.writeText(secret).catch(()=>setError('Select and copy the credential manually.'))}>Copy credential</button><button onClick={()=>setSecret('')}>Dismiss</button></div>}{active&&<><p>In Power BI Desktop: Get data → Web. In Excel: Data → Get Data → From Web (where available). Enter this URL. Choose <strong>Basic</strong> authentication, username <code>datalake</code>, and use the credential as the password. Set privacy to <strong>Private</strong>.</p><input aria-label="Power BI worksheet URL" readOnly value={url} style={{width:'100%'}}/><p>Each worksheet has its own feed URL and credentials. Refresh in Power BI or Excel after saving sheet changes here. External changes do not write back to the portal. Configure scheduled refresh separately in Power BI.</p></>}<h3>Active and expired credentials</h3>{tokens.filter(t=>!workbook||workbook.sheets.some(s=>s.id===t.dataset)).map(t=><p key={t.id}>{sheetLabel(t.dataset)} · Expires {new Date(t.expires).toLocaleDateString()} <button className="outline-button" disabled={busy} onClick={async()=>{setBusy(true);try{await post({action:'revoke',id:t.id});setSecret('');await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Revoke</button></p>)}<h2>SQL tools</h2><p>Download a SQLite database of the open worksheet to use in your SQL tool, or use the SQL workspace here. This portal does not expose a SQL Server or PostgreSQL network connection.</p><button className="outline-button" disabled={!data||busy} onClick={()=>query('export')}>Download SQLite database</button><p>Exports leave portal access controls once downloaded. Store them in your company’s approved location.</p></div>}
 {tab==='audit'&&<div className="tool-card"><h2>Recent server access</h2><button className="outline-button" onClick={()=>refresh().catch(e=>setError(e.message))}>Refresh log</button><p>Imports, worksheet reads, credential changes, and external reads. Local SQL queries and actions on downloaded copies are not logged.</p><div className="orders-table"><table><thead><tr><th>Time</th><th>Action</th><th>Workbook / worksheet / credential</th><th>Actor ID</th></tr></thead><tbody>{audit.map((a,i)=><tr key={i}><td>{new Date(a.created).toLocaleString()}</td><td>{a.action}</td><td>{workbooks.find(w=>w.id===a.dataset)?.name||sheetLabel(a.dataset)}</td><td>{a.actor}</td></tr>)}</tbody></table></div></div>}
 {busy&&<p role="status">{progress||'Working…'} {processing&&<button className="outline-button" onClick={()=>cancelTask.current?.()}>Cancel operation</button>}</p>}</>}</section>;
}
