'use client';
import LiveWixInventory from './live-wix-inventory';
import {useEffect,useState,useRef} from 'react';
import {ExternalLink,Package,RefreshCw,ScanLine} from 'lucide-react';
import {Skeleton} from '@/components/ui/skeleton';
import InventoryScanner from './inventory-scanner';
import type {InventoryProduct} from '@/lib/inventory';
type Data={loaded:boolean;snapshot:boolean;loadedAt:string;total:number;sites:{id:string;name:string;supported:boolean;productsUrl:string}[];products:InventoryProduct[];results:{siteId:string;total:number|null;checked:string|null;error:string}[];hasMore:boolean};
export default function InventoryView(){return <LiveWixInventory saved={<SavedInventoryView/>}/>;}
function SavedInventoryView(){
 const [data,setData]=useState<Data|null>(null),[site,setSite]=useState('faa072bb-65e2-4eeb-95d8-6d5b668a8282'),[query,setQuery]=useState(''),[sort,setSort]=useState('name_asc'),[page,setPage]=useState(0),[attempt,setAttempt]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState('');

 const [scanOpen,setScanOpen]=useState(false),[referenceProduct,setReferenceProduct]=useState<InventoryProduct|null>(null);
 const sentinel=useRef<HTMLDivElement>(null),loadLock=useRef(false);
 const reset=()=>{loadLock.current=true;setPage(0);setError('');setData(old=>old?{...old,products:[],hasMore:false}:null)};
 useEffect(()=>{
  const c=new AbortController();loadLock.current=true;setLoading(true);setError('');
  fetch('/api/inventory?'+new URLSearchParams({site,q:query,sort,page:String(page)}),{signal:c.signal,cache:'no-store'})
   .then(async r=>{const d=await r.json() as Data & {error?:string};if(c.signal.aborted)return;if(!r.ok){if(r.status===401||r.status===403)setData(null);throw Error(d.error||'Inventory could not load.')}
    setData(old=>{if(page===0||!old)return d;const seen=new Set(old.products.map(p=>p.siteId+p.id));return {...d,products:[...old.products,...d.products.filter(p=>!seen.has(p.siteId+p.id))]}})})
   .catch(e=>{if(!c.signal.aborted)setError(e.message)})
   .finally(()=>{if(!c.signal.aborted){loadLock.current=false;setLoading(false)}});
  return()=>c.abort();
 },[site,query,sort,page,attempt]);
 useEffect(()=>{
  if(loading||error||!data?.hasMore||!sentinel.current)return;
  const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)&&!loadLock.current){loadLock.current=true;setPage(p=>p+1)}},{rootMargin:'300px'});
  observer.observe(sentinel.current);return()=>observer.disconnect();
 },[loading,error,data?.hasMore,data?.products.length]);

 const money=(p:InventoryProduct)=>{if(p.price===null)return 'Not supplied';try{return new Intl.NumberFormat(undefined,{style:'currency',currency:p.currency,currencyDisplay:'code'}).format(p.price)}catch{return p.price+' '+p.currency}};
 return <section className="workspace-tool orders-workspace"><div className="tool-title"><h1>Inventory</h1><div className="scan-actions"><button className="outline-button" disabled={!data} onClick={()=>setScanOpen(true)}><ScanLine size={18}/>Scan painting</button><button className="outline-button" disabled={loading} onClick={()=>{reset();setAttempt(v=>v+1)}}><RefreshCw size={16}/>Reload table</button></div></div><p className="tool-intro">Product information and quantities across your Wix websites. The main Rebecca Aldernet store is your stock reference.</p>{error&&<p role="alert" className="error-banner">{error}</p>}{loading&&!data?<Skeleton className="h-48 w-full"/>:data&&<>
 <p className="order-data-note">Loaded from Wix {new Date(data.loadedAt).toLocaleString()}. This table shows imported quantities; automatic shared-stock updates are not enabled.</p>
 <div className="order-filters"><label>Website<select value={site} onChange={e=>{reset();setSite(e.target.value)}}><option value="">All websites</option>{data.sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Find a product<input type="search" value={query} onChange={e=>{reset();setQuery(e.target.value)}} placeholder="Product name or SKU"/></label><label>Sort by<select value={sort} onChange={e=>{reset();setSort(e.target.value)}}><option value="name_asc">Product name: A–Z</option><option value="name_desc">Product name: Z–A</option><option value="quantity_asc">Quantity: low to high</option><option value="quantity_desc">Quantity: high to low</option><option value="price_asc">Price: low to high, by currency</option><option value="price_desc">Price: high to low, by currency</option></select></label></div>
 <details><summary>Website catalogs</summary><div className="metric-grid">{data.sites.filter(s=>!site||s.id===site).map(s=>{const r=data.results.find(r=>r.siteId===s.id);return <div className="tool-card" key={s.id}><strong>{s.name}</strong><p>{!s.supported?'No Wix Stores catalog':!data.loaded?'Connection required':r?.error||((r?.total??'—').toLocaleString()+' products')}</p>{r?.checked&&<small>Checked {new Date(r.checked).toLocaleString()}</small>}{s.supported&&<p><a className="outline-button" href={s.productsUrl} target="_blank" rel="noopener noreferrer">Open products in Wix <ExternalLink size={14}/></a></p>}</div>})}</div></details>
 {data.loaded&&<><div className="orders-table" aria-busy={loading}><table><caption className="sr-only">Imported Wix product listings</caption><thead><tr><th>Product</th><th>Website</th><th>SKU</th><th>Base price</th><th>Availability</th><th>Quantity</th><th>Visibility</th><th>Reference photo</th><th>Product page</th></tr></thead><tbody>{data.products.map(p=><tr key={p.siteId+p.id}><td><a href={p.productUrl||p.url} target="_blank" rel="noopener noreferrer" className="inventory-product-link" aria-label={p.name+(p.productUrl?' — view product on website (new tab)':' — view in Wix (new tab)')}>{p.image?<img src={p.image} alt="" width={56} height={56} loading="lazy" decoding="async"/>:<Package size={28}/>}<span><strong>{p.name}</strong>{!p.productUrl&&<small>{p.linkStatus==='unpublished'?'Website unpublished · Opens Wix':p.linkStatus==='hidden'?'Hidden product · Opens Wix':p.linkStatus==='not-found'?'No longer returned by Wix · View saved listing':'Website link unavailable · Opens Wix'}</small>}</span><ExternalLink size={14}/></a></td><td>{data.sites.find(s=>s.id===p.siteId)?.name}</td><td>{p.sku||'—'}</td><td>{money(p)}</td><td>{p.inStock===null?'Not supplied':<span className={p.inStock?'inventory-stock-label inventory-stock-in':'inventory-stock-label inventory-stock-out'}>{p.inStock?'In stock':'Out of stock'}</span>}</td><td>{p.quantity??(p.variants?'See variants':p.tracked?'Not supplied':'Not tracked')}</td><td>{p.visible?'Visible':'Hidden'}</td><td><button className="outline-button" onClick={()=>setReferenceProduct(p)}>Add reference photo</button></td><td><a href={p.productUrl||p.url} target="_blank" rel="noopener noreferrer" className="outline-button">{p.productUrl?'View product':'View in Wix'} <ExternalLink size={14}/></a></td></tr>)}{!data.products.length&&<tr><td colSpan={9}>{data.results.some(r=>r.error)?'Some catalogs could not load. See the website status above.':loading?'Loading products…':'No matching products.'}</td></tr>}</tbody></table></div><div className="orders-footer"><span>{data.products.length.toLocaleString()} of {data.total.toLocaleString()} matching listings{sort.startsWith('price')?' · Prices sorted within each currency.':''}</span></div><div ref={sentinel} className="py-5 text-center" role="status" aria-live="polite">{loading?'Loading products…':error?<button className="outline-button" onClick={()=>setAttempt(v=>v+1)}>Retry loading</button>:data.hasMore?'Scroll down for more products':data.products.length?'All matching products loaded.':''}</div></>}
 </>}{scanOpen&&<InventoryScanner site={site} onClose={()=>setScanOpen(false)}/>} {referenceProduct&&<InventoryScanner site={referenceProduct.siteId} product={referenceProduct} onClose={()=>setReferenceProduct(null)}/>}</section>;
}
