'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import type {InventoryProduct} from '@/lib/inventory';
type Connection={configured:boolean;canManage:boolean;ready:boolean;sites:{id:string;name:string;connected:boolean}[];includeHidden:boolean};
type Page={products:InventoryProduct[];total:number;hasMore:boolean;checkedAt:string};
async function result(r:Response){const d:any=await r.json();if(!r.ok)throw Error(d.error||'Request failed.');return d}
export default function LiveWixInventory({saved}:{saved:ReactNode}){
 const [connection,setConnection]=useState<Connection|null>(null),[error,setError]=useState(''),[mode,setMode]=useState('live'),[manage,setManage]=useState(false),[key,setKey]=useState(''),[selected,setSelected]=useState<string[]>([]),[hidden,setHidden]=useState(false),[saving,setSaving]=useState(false);
 const load=async()=>{const c:Connection=await fetch('/api/inventory/connection',{cache:'no-store'}).then(result);setConnection(c);setSelected(c.configured?c.sites.filter(s=>s.connected).map(s=>s.id):['faa072bb-65e2-4eeb-95d8-6d5b668a8282']);setHidden(c.includeHidden)};
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function connect(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');const apiKey=key;setKey('');try{await fetch('/api/inventory/connection',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey,sites:selected,includeHidden:hidden})}).then(result);await load();setManage(false);setMode('live')}catch(e){setError(e instanceof Error?e.message:'Could not connect.')}finally{setSaving(false)}}
 return <><div className="workspace-tool" style={{paddingBottom:0}}><div className="scan-actions"><button className="outline-button" aria-pressed={mode==='live'} onClick={()=>setMode('live')}>Live Wix inventory</button><button className="outline-button" aria-pressed={mode==='saved'} onClick={()=>setMode('saved')}>Saved inventory / scanner</button>{connection?.canManage&&<button className="outline-button" onClick={()=>setManage(v=>!v)}>{connection.configured?'Manage Wix connection':'Connect Wix inventory'}</button>}</div>{error&&<p className="error-banner" role="alert">{error}</p>}{!connection&&!error&&<p>Checking Wix connection…</p>}{connection&&!connection.configured&&<p className="order-data-note">Live inventory is not connected yet. {connection.canManage?'Enter your Wix API key below to connect.':'The owner needs to connect Wix.'}</p>}
 {connection?.canManage&&(manage||!connection.configured)&&<form onSubmit={connect} className="tool-card" style={{marginTop:16,maxWidth:700}}><h2>Connect Wix inventory</h2><p>Your key is encrypted on the server and used only to read products and stock. Enter it here, not in chat.</p><label style={{display:'block',margin:'16px 0'}}>Wix API key<input type="password" autoComplete="off" required value={key} onChange={e=>setKey(e.target.value)} style={{display:'block',width:'100%',padding:12,border:'1px solid #aaa',borderRadius:8}}/></label><fieldset><legend>Websites this key can access</legend>{connection.sites.map(s=><label key={s.id} style={{display:'block',margin:'10px 0'}}><input type="checkbox" checked={selected.includes(s.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,s.id]:old.filter(id=>id!==s.id))}/> {s.name}</label>)}</fieldset><label style={{display:'block',margin:'16px 0'}}><input type="checkbox" checked={hidden} onChange={e=>setHidden(e.target.checked)}/> Include hidden products (requires Wix Manage Products permission)</label><button className="outline-button" disabled={saving||!connection.ready||!selected.length}>{saving?'Validating with Wix…':'Connect and validate'}</button>{!connection.ready&&<p>Secure connection setup is not available yet.</p>}</form>}</div>
 {mode==='saved'?saved:connection?.configured?<LiveTable key={connection.sites.filter(s=>s.connected).map(s=>s.id).join()+connection.includeHidden} connection={connection}/>:null}</>;
}
function LiveTable({connection}:{connection:Connection}){
 const sites=connection.sites.filter(s=>s.connected),[site,setSite]=useState(sites.find(s=>s.id==='faa072bb-65e2-4eeb-95d8-6d5b668a8282')?.id||sites[0]?.id||''),[search,setSearch]=useState(''),[q,setQ]=useState(''),[sort,setSort]=useState('name_asc'),[pages,setPages]=useState<Page[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 const sentinel=useRef<HTMLDivElement>(null),refresh=useRef<(more?:boolean)=>void>(()=>{});
 useEffect(()=>{const timer=setTimeout(()=>setQ(search),300);return()=>clearTimeout(timer)},[search]);
 useEffect(()=>{
  const controller=new AbortController();let loading=false,current:Page[]=[];setPages([]);setError('');
  const read=(page:number)=>fetch('/api/inventory/live?'+new URLSearchParams({site,q,sort,page:String(page)}),{signal:controller.signal,cache:'no-store'}).then(result) as Promise<Page>;
  async function run(more=false){if(loading||controller.signal.aborted)return;loading=true;setBusy(true);try{let next:Page[];if(more){next=[...current,await read(current.length)]}else{next=[];const count=Math.max(1,current.length);for(let i=0;i<count;i+=4){next.push(...await Promise.all(Array.from({length:Math.min(4,count-i)},(_,j)=>read(i+j))));if(!next[next.length-1].hasMore)break;}}if(!controller.signal.aborted){current=next;setPages(next);setError('')}}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Wix could not refresh.')}finally{loading=false;if(!controller.signal.aborted)setBusy(false)}}
  refresh.current=run;run();const timer=setInterval(()=>{if(document.visibilityState==='visible')run()},60000);const visible=()=>{if(document.visibilityState==='visible')run()};document.addEventListener('visibilitychange',visible);return()=>{controller.abort();clearInterval(timer);document.removeEventListener('visibilitychange',visible)};
 },[site,q,sort,retry]);
 const last=pages[pages.length-1];
 useEffect(()=>{if(busy||error||!last?.hasMore||!sentinel.current)return;const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting))refresh.current(true)},{rootMargin:'250px'});observer.observe(sentinel.current);return()=>observer.disconnect()},[busy,error,last]);
 const products=Array.from(new Map(pages.flatMap(p=>p.products).map(p=>[p.id,p])).values());
 return <section className="workspace-tool orders-workspace"><div className="tool-title"><h1>Live Wix inventory</h1><button className="outline-button" disabled={busy} onClick={()=>refresh.current()}>Refresh now</button></div><p className="tool-intro">Current products and quantities from Wix. Refreshes every minute while this view is open. {connection.includeHidden?'Includes hidden products.':'Visible products only.'}</p>{error&&<p role="alert" className="error-banner">Refresh failed. Displayed results may be out of date. {error} <button onClick={()=>setRetry(v=>v+1)}>Retry</button></p>}<div className="order-filters"><label>Website<select value={site} onChange={e=>setSite(e.target.value)}>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Find a product<input type="search" placeholder="Product name or SKU" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="name_asc">Product name: A–Z</option><option value="name_desc">Product name: Z–A</option><option value="price_asc">Price: low to high</option><option value="price_desc">Price: high to low</option><option value="updated_desc">Recently updated</option></select></label></div><p className="order-data-note">{pages[0]?`${pages[0].total.toLocaleString()} products · Last checked ${new Date(pages[0].checkedAt).toLocaleString()}`:'Loading current Wix data…'}</p><div className="orders-table" aria-busy={busy}><table><caption className="sr-only">Live Wix inventory</caption><thead><tr><th>Product</th><th>SKU</th><th>Price</th><th>Availability</th><th>Quantity</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><a className="inventory-product-link" href={p.productUrl||p.url} target="_blank" rel="noopener noreferrer">{p.image&&<img src={p.image} alt="" width={56} height={56} loading="lazy"/>}<span><strong>{p.name}</strong>{!p.productUrl&&<small>Opens product in Wix</small>}</span> ↗</a></td><td>{p.sku||'—'}</td><td>{p.price===null?'Not supplied':p.price.toLocaleString()+' '+p.currency}</td><td>{p.inStock===null?'Not supplied':<span className={'inventory-stock-label '+(p.inStock?'inventory-stock-in':'inventory-stock-out')}>{p.inStock?'In stock':'Out of stock'}</span>}</td><td>{p.quantity??(p.variants?'See variants':p.tracked?'Not supplied':'Not tracked')}</td></tr>)}{!products.length&&!busy&&!error&&<tr><td colSpan={5}>No matching products.</td></tr>}</tbody></table></div><div ref={sentinel} style={{padding:20,textAlign:'center'}} role="status">{busy?'Loading Wix products…':last?.hasMore?<button className="outline-button" onClick={()=>refresh.current(true)}>Load more</button>:products.length?'All matching products loaded.':''}</div></section>;
}
