'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {permissionOptions,effectivePermissions,type Permissions,type Permission} from '@/lib/permissions';
import {toast} from 'sonner';
export default function PermissionsEditor({person,onClose,onSaved}:{person:{id:string;name:string;role:string;effectivePermissions:Permissions};onClose:()=>void;onSaved:()=>void}){
 const [rights,setRights]=useState(person.effectivePermissions),[busy,setBusy]=useState(false);
 function toggle(key:Permission,value:boolean){const next={...rights,[key]:value};if(value){if(['sendMessages','editOwnMessages','deleteOwnMessages','uploadFiles'].includes(key))next.readMessages=true;if(key==='uploadFiles'){next.sendMessages=true;next.viewFiles=true;}if(key==='downloadFiles')next.viewFiles=true;}setRights(effectivePermissions({role:person.role,permissions:JSON.stringify(next)}));}
 async function save(){setBusy(true);try{const r=await fetch('/api/access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'permissions',id:person.id,permissions:rights})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'Could not save permissions');toast.success('Member permissions saved');onSaved();onClose()}catch(e){toast.error(e instanceof Error?e.message:'Could not save permissions')}finally{setBusy(false)}}
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose()}}><DialogContent className="permissions-dialog"><DialogHeader><DialogTitle>Permissions for {person.name}</DialogTitle><DialogDescription>Changes apply across all channels. Related rights are adjusted together. Previously downloaded files cannot be recalled.</DialogDescription></DialogHeader><div className="permission-presets"><button className="outline-button" disabled={busy} onClick={()=>setRights({...effectivePermissions({role:'member'}),sendMessages:false,editOwnMessages:false,deleteOwnMessages:false,uploadFiles:false,createChannels:false,viewAnalytics:false})}>Read only</button><button className="outline-button" disabled={busy} onClick={()=>setRights(effectivePermissions({role:person.role}))}>Role defaults</button></div><div className="permission-list">{permissionOptions.map(p=><div className="setting-row" key={p.key}><label htmlFor={'permission-'+p.key}><strong>{p.label}</strong><span>{p.description}</span></label><Switch id={'permission-'+p.key} checked={rights[p.key]} disabled={busy||(!['owner','admin'].includes(person.role)&&['viewOrders','viewInventory'].includes(p.key))} onCheckedChange={v=>toggle(p.key,v)}/></div>)}</div><p className="access-help">Admin promotion, permission assignments, and joining rules remain owner-only. Editing and deleting other people’s messages is not supported.</p><div className="edit-actions"><button className="outline-button" disabled={busy} onClick={onClose}>Cancel</button><button className="solid-button" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save permissions'}</button></div></DialogContent></Dialog>
}
