'use client';
import {ArrowUpRight,MessageSquare,Users,Globe,Package,ShoppingBag,BarChart3,Files,Settings,Hash,ArrowRight} from 'lucide-react';
import type {Permissions} from '@/lib/permissions';
type Props={name:string;rights:Permissions;ready:boolean;error:string;channels:{id:string;name:string;description:string}[];unread:{channelTotal:number;directTotal:number;mentionTotal:number;counts:Record<string,number>;error:string};onNavigate:(view:string)=>void;onChannel:(id:string)=>void};
export default function PortalHome({name,rights,ready,error,channels,unread,onNavigate,onChannel}:Props){
 const tools=[
  {view:'wix',title:'Websites',description:'Visit each store, open Wix editors, and check website analytics.',icon:Globe,allowed:true},
  {view:'orders',title:'Orders',description:'Review received orders and open the sales reports in Wix.',icon:ShoppingBag,allowed:rights.viewOrders},
  {view:'inventory',title:'Inventory',description:'Find products, compare quantities, and check availability.',icon:Package,allowed:rights.viewInventory},
  {view:'analytics',title:'Studio analytics',description:'Understand team conversations and shared-file activity.',icon:BarChart3,allowed:rights.viewAnalytics},
  {view:'files',title:'Shared files',description:'Find and download files from your selected team channel.',icon:Files,allowed:rights.viewFiles},
  {view:'team',title:'Team directory',description:'Find a colleague and start a private conversation.',icon:Users,allowed:rights.readMessages},
 ];
 return <section className="workspace-tool portal-home">
  <div className="portal-heading"><div><span className="portal-eyebrow">RA STUDIO · COMPANY PORTAL</span><h1>Welcome, {name.split(' ')[0]}.</h1><p>Your team, stores, and daily work in one place.</p></div><button className="outline-button" onClick={()=>onNavigate('settings')}><Settings size={17}/>My settings</button></div>
  {error&&<p role="alert" className="error-banner">{error}</p>}
  <div className="portal-inbox"><div><MessageSquare size={24}/><div><h2>Your inbox</h2><p>{!ready?'Loading workspace…':!rights.readMessages?'Conversation access is managed by your administrator.':unread.error||'Open a conversation to read and clear its unread messages.'}</p></div></div><div className="portal-inbox-actions">{[{view:'messages',label:'Channel messages',count:unread.channelTotal},{view:'direct',label:'Private messages',count:unread.directTotal},{view:'messages',label:'Mentions',count:unread.mentionTotal}].map(x=><button key={x.label} disabled={!ready||!rights.readMessages} onClick={()=>onNavigate(x.view)}><strong>{!ready||!rights.readMessages||unread.error?'—':x.count}</strong><span>{x.label}</span><ArrowUpRight size={17}/></button>)}</div></div>
  <div className="portal-section-heading"><h2>Company tools</h2><span>Access follows your assigned permissions</span></div>
  <div className="portal-tools">{tools.filter(t=>!(['orders','inventory'].includes(t.view))||t.allowed).map(t=><button className="portal-tool" key={t.view} disabled={!ready||!t.allowed} onClick={()=>onNavigate(t.view)}><div className="portal-tool-top"><t.icon size={23}/><ArrowUpRight size={18}/></div><h3>{t.title}</h3><p>{t.description}</p><span>{!ready?'Loading access…':t.allowed?'Open '+t.title.toLowerCase():'Access restricted'}</span></button>)}</div>
  <div className="portal-bottom"><section className="portal-panel"><div className="portal-section-heading"><h2>Team channels</h2><Hash size={19}/></div>{!ready?<p>Loading channels…</p>:!rights.readMessages?<p>Contact an administrator for conversation access.</p>:channels.length?channels.map(c=><button className="portal-channel" key={c.id} onClick={()=>onChannel(c.id)}><Hash size={19}/><span><strong>{c.name}</strong><small>{c.description}</small></span>{unread.counts[c.id]>0&&<b className="unread-badge">{unread.counts[c.id]}</b>}<ArrowRight size={17}/></button>):<p>No channels available yet.</p>}</section>
  <section className="portal-panel"><h2>Connections & access</h2>{ready&&rights.viewInventory&&<div className="portal-connection"><span className="portal-pending">Setup pending</span><h3>Wix inventory sync</h3><p>Inventory currently shows an imported snapshot. New products and stock changes need another import until the Wix API connection is configured.</p><button className="text-button" onClick={()=>onNavigate('inventory')}>Review inventory <ArrowRight size={15}/></button></div>}<div className="portal-connection"><h3>Website access</h3><p>Wix editors and reports open in another tab. Each colleague signs in with their own Wix permissions.</p><button className="text-button" onClick={()=>onNavigate('wix')}>Open websites <ArrowRight size={15}/></button></div>{ready&&rights.manageMembers&&<div className="portal-connection"><h3>Workspace administration</h3><p>Approve colleagues, manage membership, and review access in Settings.</p><button className="text-button" onClick={()=>onNavigate('settings')}>Manage workspace access <ArrowRight size={15}/></button></div>}</section></div>
 </section>;
}
