'use client';
import {useEffect,useState} from 'react';
import {Globe,ExternalLink,Pencil,Loader2,BarChart3} from 'lucide-react';
type WixSite={id:string;name:string;url:string|null;editorUrl:string|null;dashboardUrl:string;analyticsUrl:string;status:string};
export default function WixDashboard(){
 const [sites,setSites]=useState<WixSite[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');fetch('/api/wix-sites',{cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json() as {sites:WixSite[];error?:string};if(!r.ok)throw Error(d.error||'Could not load websites.');setSites(d.sites)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[attempt]);
 return <section className="workspace-tool wix-workspace"><div className="wix-heading"><div><span className="eyebrow">WEBSITES</span><h1>Wix dashboard</h1><p>Visit your websites, open their editors, or check their analytics.</p></div><a className="outline-button" href="https://manage.wix.com/account/websites" target="_blank" rel="noopener noreferrer">Open Wix<ExternalLink size={16}/></a></div><p className="wix-access-note">Editors and analytics open in a new tab and require your own Wix account permissions.</p>{loading?<p role="status"><Loader2 className="animate-spin" size={18}/>Loading websites…</p>:error?<div role="alert">{error} <button className="text-button" onClick={()=>setAttempt(attempt+1)}>Try again</button></div>:<><div className="wix-site-count">{sites.length} websites · Links checked September 14, 2026</div><div className="wix-site-grid">{sites.map(site=><article className="wix-site-card" key={site.id}><div className="wix-card-top"><span className="wix-site-icon"><Globe size={24}/></span><span className="wix-status">{site.status}</span></div><h2>{site.name}</h2><p className="wix-address">{site.url?new URL(site.url).hostname:site.status==='Draft'?'No published website yet':'Public address unavailable'}</p><div className="wix-actions">{site.url?<a className="outline-button" href={site.url} target="_blank" rel="noopener noreferrer"><ExternalLink size={15}/>Visit site</a>:<button className="outline-button" disabled title="No published address is available">Visit site</button>}{site.editorUrl?<a className="solid-button" href={site.editorUrl} target="_blank" rel="noopener noreferrer"><Pencil size={15}/>Edit this site</a>:<button className="solid-button" disabled title="Wix did not return an editor link">Edit this site</button>}<a className="outline-button" href={site.analyticsUrl} target="_blank" rel="noopener noreferrer" aria-label={`View analytics for ${site.name}`}><BarChart3 size={15}/>View analytics</a></div><a className="wix-dashboard-link" href={site.dashboardUrl} target="_blank" rel="noopener noreferrer">Site dashboard <ExternalLink size={13}/></a></article>)}</div></>}</section>;
}
