import { sqliteTable, text, integer, index, primaryKey } from 'drizzle-orm/sqlite-core';
export const channels = sqliteTable('channels', { id:text('id').primaryKey(), name:text('name').notNull().unique(), description:text('description').notNull(), created:integer('created').notNull() });
export const messages = sqliteTable('messages', { id:text('id').primaryKey(), channel:text('channel').notNull(), author:text('author').notNull(), userId:text('user_id').notNull(), body:text('body').notNull(), reply:text('reply'), pinned:integer('pinned').notNull().default(0), mentions:text('mentions').notNull().default('{}'), edited:integer('edited'), created:integer('created').notNull() },t=>[index('idx_messages_channel_created').on(t.channel,t.created)]);
export const files = sqliteTable('files', { id:text('id').primaryKey(), messageId:text('message_id').notNull(), channel:text('channel').notNull(), name:text('name').notNull(), size:integer('size').notNull(), type:text('type').notNull(), author:text('author').notNull(), created:integer('created').notNull() },t=>[index('idx_files_channel_created').on(t.channel,t.created)]);
export const members = sqliteTable('members', {id:text('id').primaryKey(),userId:text('user_id').unique(),email:text('email').unique(),name:text('name').notNull(),role:text('role').notNull().default('member'),permissions:text('permissions').notNull().default('{}'),status:text('status').notNull().default('active'),created:integer('created').notNull()});
export const accessSettings = sqliteTable('access_settings', {id:text('id').primaryKey(),requireApproval:integer('require_approval').notNull().default(0)});

export const messageNotifications = sqliteTable('message_notifications', {seq:integer('seq').primaryKey({autoIncrement:true}),messageId:text('message_id').notNull().unique(),channel:text('channel').notNull(),sender:text('sender').notNull()},t=>[index('idx_message_notifications_channel_seq').on(t.channel,t.seq)]);
export const channelReads = sqliteTable('channel_reads', {userId:text('user_id').notNull(),channel:text('channel').notNull(),lastSeq:integer('last_seq').notNull().default(0)},t=>[primaryKey({columns:[t.userId,t.channel]})]);

export const uploadSessions = sqliteTable('upload_sessions', {id:text('id').primaryKey(),owner:text('owner').notNull(),batch:text('batch').notNull(),channel:text('channel').notNull(),name:text('name').notNull(),size:integer('size').notNull(),type:text('type').notNull(),uploadId:text('upload_id').notNull(),state:text('state').notNull().default('uploading'),created:integer('created').notNull()},t=>[index('idx_upload_sessions_owner_batch').on(t.owner,t.batch)]);

export const directThreads = sqliteTable('direct_threads', {id:text('id').primaryKey(),memberA:text('member_a').notNull(),memberB:text('member_b').notNull(),created:integer('created').notNull()},t=>[index('idx_direct_pair').on(t.memberA,t.memberB)]);
export const directMessages = sqliteTable('direct_messages', {seq:integer('seq').primaryKey({autoIncrement:true}),id:text('id').notNull().unique(),thread:text('thread').notNull(),sender:text('sender').notNull(),body:text('body').notNull(),created:integer('created').notNull()},t=>[index('idx_direct_messages_thread_seq').on(t.thread,t.seq)]);
export const directReads = sqliteTable('direct_reads', {memberId:text('member_id').notNull(),thread:text('thread').notNull(),lastSeq:integer('last_seq').notNull().default(0)},t=>[primaryKey({columns:[t.memberId,t.thread]})]);

export const websiteOrders = sqliteTable('website_orders', {sourceUpdated:integer('source_updated').notNull().default(0),siteId:text('site_id').notNull(),orderId:text('order_id').notNull(),orderNumber:text('order_number').notNull(),created:integer('created').notNull(),customer:text('customer').notNull(),email:text('email').notNull(),currency:text('currency').notNull(),total:text('total').notNull(),payment:text('payment').notNull(),fulfillment:text('fulfillment').notNull(),status:text('status').notNull(),items:text('items').notNull(),shipping:text('shipping').notNull(),note:text('note').notNull(),received:integer('received').notNull()},t=>[primaryKey({columns:[t.siteId,t.orderId]}),index('idx_website_orders_created').on(t.created)]);

export const orderClassifications = sqliteTable('order_classifications', {siteId:text('site_id').notNull(),orderId:text('order_id').notNull(),segment:text('segment').notNull(),updatedBy:text('updated_by').notNull(),updated:integer('updated').notNull()},t=>[primaryKey({columns:[t.siteId,t.orderId]})]);

export const inventoryReferences = sqliteTable('inventory_references', {id:text('id').notNull().unique(),siteId:text('site_id').notNull(),productId:text('product_id').notNull(),objectKey:text('object_key').notNull(),signature:text('signature').notNull(),updated:integer('updated').notNull()},t=>[primaryKey({columns:[t.siteId,t.productId]})]);

export const memberPresence=sqliteTable('member_presence',{memberId:text('member_id').notNull(),sessionId:text('session_id').notNull(),sequence:integer('sequence').notNull(),active:integer('active').notNull(),seen:integer('seen').notNull()},t=>[primaryKey({columns:[t.memberId,t.sessionId]}),index('idx_member_presence_seen').on(t.seen)]);

export const lakeDatasets=sqliteTable('lake_datasets',{id:text('id').primaryKey(),name:text('name').notNull(),columns:text('columns').notNull(),rowCount:integer('row_count').notNull(),objectKey:text('object_key').notNull(),created:integer('created').notNull(),owner:text('owner').notNull()});
// One uploaded workbook groups an ordered list of worksheets. Legacy single-sheet datasets are copied into
// these tables by migration 0016 with workbook id = sheet id = original dataset id so feed credentials keep working.
export const lakeWorkbooks=sqliteTable('lake_workbooks',{id:text('id').primaryKey(),name:text('name').notNull(),state:text('state').notNull().default('staging'),revision:text('revision').notNull(),sheetCount:integer('sheet_count').notNull().default(0),bytes:integer('bytes').notNull().default(0),created:integer('created').notNull(),updated:integer('updated').notNull(),owner:text('owner').notNull()},t=>[index('idx_lake_workbooks_state_created').on(t.state,t.created)]);
export const lakeSheets=sqliteTable('lake_sheets',{id:text('id').primaryKey(),workbook:text('workbook').notNull(),position:integer('position').notNull(),name:text('name').notNull(),columns:text('columns').notNull(),rowCount:integer('row_count').notNull(),bytes:integer('bytes').notNull().default(0),objectKey:text('object_key').notNull(),created:integer('created').notNull(),updated:integer('updated').notNull()},t=>[index('idx_lake_sheets_workbook_position').on(t.workbook,t.position)]);
export const lakeTokens=sqliteTable('lake_tokens',{id:text('id').primaryKey(),dataset:text('dataset').notNull(),hash:text('hash').notNull().unique(),owner:text('owner').notNull(),expires:integer('expires').notNull(),created:integer('created').notNull()});
export const lakeAudit=sqliteTable('lake_audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),dataset:text('dataset').notNull(),created:integer('created').notNull()},t=>[index('idx_lake_audit_created').on(t.created)]);
